version: "3"
services:
  notifications-api:
    build: .
    restart: always
    container_name: notifications-service
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mysqldb
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_PORT/$MYSQL_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_PASSWORD",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.mail.host":"$SPRING_MAIL_HOST",
        "spring.mail.port":$SPRING_MAIL_PORT,
        "spring.mail.username": "$SPRING_MAIL_USERNAME",
        "spring.mail.password":"$SPRING_MAIL_PASSWORD",
        "spring.mail.properties.mail.smtp.auth":"$SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH",
        "spring.mail.properties.mail.smtp.starttls.enable": "$SPRING_MAIL_PROPERTIES_MAIL_STARTTLS_ENABLE"
      }'

    networks:
      - sorcerers_network
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    ports:
      - "3307:3306"
    env_file:
      - .env
    networks:
      - sorcerers_network

networks:
  sorcerers_network:
    driver: bridge